// Group action types
export const LOAD_GROUPS_SUCCESS = "LOAD_GROUPS_SUCCESS";
export const ADD_ATTRIBUTE_SUCCESS = "ADD_ATTRIBUTE_SUCCESS";
export const REMOVE_ATTRIBUTE_SUCCESS = "REMOVE_ATTRIBUTE_SUCCESS";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";

// Interview action types
export const CREATE_INTERVIEW_SUCCESS = "CREATE_INTERVIEW_SUCCESS";
export const UPDATE_INTERVIEW_SUCCESS = "UPDATE_INTERVIEW_SUCCESS";
export const LOAD_INTERVIEWS_SUCCESS = "LOAD_INTERVIEWS_SUCCESS";

// Test action types
export const LOAD_TESTS_SUCCESS = "LOAD_TESTS_SUCCESS";
export const CREATE_TEST_SUCCESS = "CREATE_TEST_SUCCESS";
export const UPDATE_TEST_SUCCESS = "UPDATE_TEST_SUCCESS";

// Process action types
export const LOAD_PROCESSES_SUCCESS = "LOAD_PROCESSES_SUCCESS";
export const CREATE_PROCESS_SUCCESS = "CREATE_PROCESS_SUCCESS";
export const UPDATE_PROCESS_SUCCESS = "UPDATE_PROCESS_SUCCESS";
